language: ruby
rvm:
  - "1.9.3"
install:
  - sudo apt-get update
  - sudo apt-get install -y virtualbox --fix-missing
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg --install vagrant_1.7.2_x86_64.deb
  - VBoxManage -v
  - whoami=`whoami`
  - sudo usermod -a -G vboxusers $whoami
script:
  - sudo su -c "vagrant up"
